books/urls.py
# books/urls.py

"""this is the url route for app named books"""
from django.urls import path

from books import views

app_name = 'books'
urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('detail/<uuid:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('search/', views.SearchResultListView.as_view(), name='search_results'),

]

bookstore_project/urls.py
# bookstore_project/urls.py
"""bookstore_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),

    # # User management
    # path('accounts/', include('django.contrib.auth.urls')),    # new
    path('accounts/', include('allauth.urls')),    # new

    # Local apps
    # path('accounts/', include('users.urls')),    # new
    path('', include('pages.urls')),    # new
    path('books/', include('books.urls')),    # new



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # new


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)),
    ]+ urlpatterns

"""to show the
files locally."""


"""Django’s auth app looks for templates within a templates/registration directory,
but django-allauth prefers they be located within a templates/account directory"""

"""We do
this by adding an account_ prefix so Django’s 'logout' will now be 'account_logout' ,
'login' will be 'account_login' , and signup will be account_signup ."""



"""We can
create any route we like but it’s common to use the same accounts/ one used by the
default auth app. Note that it’s important to include the path for users.urls below:
URL paths are loaded top-to-bottom so this ensures that any auth URL paths will be
loaded first."""


"""accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
https://docs.djangoproject.com/en/3.0/topics/auth/default/#module-django.contrib.auth.views
"""

pages/urls.py
# pages/urls.py
"""This is the section for app named pages. This contains all urls route via pages app"""
from django.urls import path
from pages import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),

]

# template_name = 'registration/login.html' for LoginView() in django

users/urls.py
# users/urls.py
""" This is the url route for app named pages"""
from django.urls import path
# # from users.views import SignUpPageView
#
# urlpatterns = [
#     # path('signup/', SignUpPageView.as_view(), name='signup'),
# ]

books/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.db.models import Q
from django.urls import reverse


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to='covers/', blank=True)
    # slug_book = models.SlugField(max_length=10, unique= True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:book_detail', args=[str(self.id), ])  # id or pk , we can use any one.
        # we can use kwargs= {'pk':self.pk}


class Review(models.Model):
    # default object(from detail whatever sent) or (book).review_set.all / now object.review.all
    book = models.ForeignKey(Book, related_name='reviews', on_delete=models.CASCADE)
    review_body = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.review_body

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CustomUser(AbstractUser):
    pass

users/forms.py
# users/forms.py
# from django.contrib.auth import get_user_model
# from django.contrib.auth.forms import UserCreationForm, UserChangeForm

"""We’re also not using CustomUserCreationForm anymore, but instead, that provided
by django-allauth"""
#
# class CustomUserCreationForm(UserCreationForm):
#     class Meta:
#         """The password field is implicitly included by default
#         and so does not need to be explicitly named here as well. Except for these I need to add all other fields"""
#         model = get_user_model()
#         fields = ('email', 'username',)
#
#
# class CustomUserChangeForm(UserChangeForm):
#     """It has three fields: username (from the user model), password1, and password2. It verifies that password1
#     and password2 match, validates the password using validate_password(), and sets the user’s password using
#     set_password()."""
#
#     class Meta:
#         model = get_user_model()
#         fields = ('email', 'username',)
#

"""Other fields for AbstractUser i.e get_user_model()username, email, is_staff, is_active, is_superuser,
last_login, and date_joined"""

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from books.models import Book


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    template_name = 'books/book_list.html'
    context_object_name = 'book_list'  # default context_object_name = 'object_list'
    login_url = 'account_login' # if a non user tries to access the list directly then it redirects to login page


class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = 'books/book_detail.html'
    context_object_name = 'book_object'  # default context_object_name = 'book' just lowercase the name of model
    login_url = 'account_login'


class SearchResultListView(ListView):
    model = Book
    # queryset = Book.search_book_object.all()
    context_object_name = 'book_list'
    template_name = 'books/search_results.html'

    def get_queryset(self):  # for search results
        query = self.request.GET.get('q')
        return Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))

pages/views.py
# pages/views/py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class HomePageView(TemplateView):
    template_name = 'pages/home.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

users/views.py
# users/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
# from users.forms import CustomUserCreationForm
# Create your views here


# class SignUpPageView(CreateView):
#     form_class = CustomUserCreationForm
#     template_name = 'users/signup.html'
#     success_url = reverse_lazy('login')

books/templates/books/book_detail.html
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Book Detail {% endblock title %}</title>
</head>
<body>
{% block content %}
<div class="col-md-2 px-0">
    <img class="img-fluid" src="{{ book_object.cover.url }}" alt="{{ book_object.title }}">
</div>
<div>
    <h3>{{ book_object.title }}</h3>
    <p> Author : {{ book_object.author }} |
        Price : Rs {{ book_object.price }}</p>
</div>

<h3> Reviews </h3>
<div>
    <ul>
        {% for review in book_object.reviews.all %}
        <li>{{ review.author }}<br> {{ review.review_body }} </li>
        <hr>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

</body>
</html>

books/templates/books/book_list.html
<!--books/book_list.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Book List {% endblock title %}</title>
</head>
<body>
{% block content %}
<h1> Books</h1><hr>
    {% for book in book_list %}
        <div>
            <h3>
                <a href="{{ book.get_absolute_url }}">{{ book.title|title }}</a>
            </h3>
        </div>

    {% endfor %}

{% endblock content %}

</body>
</html>

books/templates/books/search_results.html
<!--books/search_result.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Search {% endblock title %}</title>
</head>
<body>
{% block content %}
<h4>Search Results</h4>
Found {{ book_list|length }} book{{book_list|pluralize}}.
<hr>
{% for book in book_list %}
    <div>
        <h4><a href="{{ book.get_absolute_url }}"> {{ book.title }}</a> </h4>
        <p>Author: {{ book.author }} | Price: Rs {{ book.price }} </p>
    </div>
{% endfor %}
{% endblock content %}
</body>
</html>

pages/templates/_base.html
<!--templates/_base.html-->
{% load static %}
{% load socialaccount %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title  %}Bookstore {% endblock title %}</title>
    <!--    CSS-->
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock css %}
</head>
<body>
    <header>
       <!-- Fixed navbar -->
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <a class="navbar-brand my-0 mr-md-auto font-weight-normal" href="{% url 'home' %}">Bookstore</a>
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
                <a class="p-2 text-dark" href="{% url 'books:book_list' %}">Books</a>
                    {% if user.is_authenticated %}
                        <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a> |
                        <strong class="p-2 text-dark">Hi {{ user.username }}, Welcome </strong>
                    {% else %}
                        <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
                        <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
                    {% endif %}
            </nav>
        </div>
    </header>
<div class="container">
{% block content %}
{% endblock content %}
</div>

    <!--Java Script-->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
{% block javascript %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock javascript %}
</body>
</html>




<!--We do-->
<!--this by adding an account_ prefix so Django’s 'logout' will now be 'account_logout' ,-->
<!--'login' will be 'account_login' , and signup will be account_signup .-->

pages/templates/pages/about.html
<!--pages/about.html-->
{% extends '_base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} About {% endblock title %}</title>
</head>
<body>
{% block content %}
<h1>About</h1>
<p>This is the about section of this page. This page will guide you throughout your website journey!!</p>
{% endblock content %}
</body>
</html>

pages/templates/pages/home.html
<!--pages/home.html-->
{% extends '_base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title  %} Homepage {% endblock title %}</title>
</head>
<body>
    {% block content %}

    <form class="form-inline mt-2 mt-md-0" action="{% url 'books:search_results' %}"method="get">
        <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
    </form>

    <div class="container">
        <h1> Homepage</h1>
        <div class="col-md-3 px-0">
            <img class="img-fluid" src="{% static 'images/dikshant_photo.jpg' %} ">
        </div>
    </div>
    {% if user.is_authenticated %}
    <!--    https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#fields-->
        <p>Hi {{ user.username }}, Welcome. |
        <a href="{% url 'account_logout' %}">Logout</a>
        </p>

    {% else %}
        <p> You are not logged in!! | Members
        <a href="{% url 'account_login' %}">Log In</a> | New User <a href="{% url 'account_signup'  %}">Signup</a>
        </p>
    {% endif %}
    {% endblock content %}
</body>
</html>